= Yet another shell configuration repository

image::https://github.com/replicajune/shellconfig/workflows/Shellcheck/badge.svg[link=https://github.com/replicajune/shellconfig/actions]

[.lead]
This repo is hosting various functions, alias and other shell configuration (hence the name) to help me be faster at doing computer stuff. Some items may come and go as I use them, or not.

== Setup

To help having some flexibility on how the repo works, I expect the local clone to be in your home folder and named `.shellconfig`:

[bash]
----
git clone git@github.com:replicajune/shellconfig.git ~/.shellconfig
----

To use it, source `shellconfig.sh` file into your user or your root `.bashrc`:

[bash]
----
#!/usr/bin/env bash

if [ -f "/home/${SUDO_USER-$USER}/.shellconfig/shellconfig.sh" ]; then
  # shellcheck source=/dev/null
  . "/home/${SUDO_USER-$USER}/.shellconfig/shellconfig.sh"
fi
----

TIP: If you prefer avoiding your computer to randomly link:https://www.imdb.com/title/tt2543312[Halt and Catch Fire], you can just take a look at the configs themselves and pick what you like :)

== Previous version

This repo used to be basically only one file. This had some limitation for me but if you'd like to see the latest version of this repo using said approach, please see link:https://github.com/replicajune/shellconfig/tree/8ace2bb94fb8ec1b1d82c84642e8cdeb793eba6c[8ace2bb]
