= Yet another shell configuration repository

[![Actions Status](https://github.com/replicajune/shellconfig/workflows/Shellcheck/badge.svg)](https://github.com/replicajune/shellconfig/actions)

This repo is hosting various functions, alias and other shell configuration (hence the name) to help me be faster at stuff I already know and have more time for other things.

WARNING: I will not be held responsible if your computer suddenly link:https://www.imdb.com/title/tt2543312[Halt and Catch Fire]. Some config will come and go as I use them, or not.

== Setup

To help having some flexibility on how the repo works, I expect the local clone to be in your home folder and named `.shellconfig`:

[sh]
----
git clone git@github.com:replicajune/shellconfig.git ~/.shellconfig
----

To use it, source `shellconfig.sh` file into your user's or your root's `.bashrc`:

[sh]
----
#!/usr/bin/env bash

if [ -f "/home/${SUDO_USER-$USER}/.shellconfig/shellconfig.sh" ]; then
  # shellcheck source=/dev/null
  . "/home/${SUDO_USER-$USER}/.shellconfig/shellconfig.sh"
fi
----

== Previous version

This repo used to be basically only one file. This had some limitation for me but if you'd like to see the latest version of this repo using this approach, please see link:https://github.com/replicajune/shellconfig/tree/8ace2bb94fb8ec1b1d82c84642e8cdeb793eba6c[8ace2bb]
